import React, { useState } from "react";
import { X } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

const LegalPopup = ({ type, onClose }) => {
    const content = {
        privacyPolicy: {
            title: "Privacy Policy",
            text: `
At JOOD, your privacy is our priority. This Privacy Policy explains how we collect, use, and protect your information when you use our smart cooking platform.

**1. Information We Collect**
• Personal Information: Name, email address, and contact information.
• Usage Data: How you interact with JOOD, including ingredients you enter, recipes generated, and orders placed.
• Device Data: IP address, browser type, and session details.

**2. How We Use Your Information**
• To generate personalized recipes based on your ingredients.
• To process and track orders for missing ingredients.
• To improve our AI services and platform features.
• To send updates and notifications about your account or the platform.
• To provide customer support.

**3. Data Security**
We use appropriate technical and organizational measures to protect your personal information from unauthorized access, misuse, or disclosure.

**4. Your Rights**
You can:
• Access and update your personal information.
• Request deletion of your account data.
• Opt-out of marketing communications.
• Withdraw consent for data processing at any time.

**5. Changes to This Privacy Policy**
We may update this policy periodically. Changes will be communicated via the website or email notifications. Please review regularly.

**6. Contact Us**
For any privacy-related inquiries, reach us at:
• Email: support@jood.com
• Phone: +1 (123) 456-7890
      `,
        },
        termsOfService: {
            title: "Terms of Service",
            text: `
Welcome to JOOD – your Smart Cooking Assistant. By using our platform, you agree to the following terms:

**1. Acceptance of Terms**
Using JOOD means you accept our terms. If you do not agree, please refrain from using our services.

**2. User Conduct**
• Use the platform responsibly and legally.
• Do not misuse AI-generated content.
• Respect intellectual property rights of JOOD and others.

**3. Account Responsibilities**
• Keep your login credentials confidential.
• Ensure that information you provide is accurate.

**4. AI-Generated Content**
Recipes and suggestions are generated by our AI based on your input. JOOD is not liable for personal dietary issues, allergies, or outcomes.

**5. Orders**
• Users may place orders for missing ingredients from connected stores.
• JOOD facilitates orders but is not responsible for delivery delays or errors.

**6. Limitation of Liability**
JOOD is not liable for any indirect or incidental damages from using the platform or AI suggestions.

**7. Governing Law**
These terms are governed by the laws of [Your Jurisdiction]. Disputes are resolved in local courts.

**8. Updates to Terms**
We may modify these terms. Updates will be posted on this page. Continued use constitutes acceptance.

**9. Contact**
For questions regarding terms of service, contact us at:
• Email: support@jood.com
• Phone: +1 (123) 456-7890
      `,
        },
    };

    const { title, text } = content[type];

    return (
        <AnimatePresence>
            <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="fixed inset-0 z-50 bg-black bg-opacity-70 flex items-center justify-center p-4"
            >
                <motion.div
                    initial={{ scale: 0.9, opacity: 0 }}
                    animate={{ scale: 1, opacity: 1 }}
                    exit={{ scale: 0.9, opacity: 0 }}
                    transition={{ type: "spring", stiffness: 200, damping: 25 }}
                    className="relative w-full max-w-3xl mx-auto rounded-xl shadow-2xl bg-gradient-to-br from-gray-50 to-green-50 border border-green-500/20"
                >
                    {/* Header */}
                    <div className="flex justify-between items-center p-5 border-b border-green-200">
                        <h2 className="text-2xl font-semibold text-green-600">
                            {title}
                        </h2>
                        <button
                            onClick={onClose}
                            className="p-2 rounded-full transition-all duration-300 hover:bg-green-500/20 text-gray-900"
                        >
                            <X className="w-6 h-6" />
                        </button>
                    </div>

                    {/* Content */}
                    <div className="p-6 max-h-[500px] overflow-y-auto scrollbar-thin scrollbar-track-green-100 scrollbar-thumb-gray-400">
                        <div className="text-base text-gray-700 leading-relaxed">
                            <pre className="whitespace-pre-wrap font-sans">
                                {text.split("\n").map((line, index) => (
                                    <span
                                        key={index}
                                        className={
                                            line.trim().startsWith("**")
                                                ? "font-semibold text-gray-900"
                                                : ""
                                        }
                                    >
                                        {line.replace(/\*\*/g, "")}
                                        <br />
                                    </span>
                                ))}
                            </pre>
                        </div>
                    </div>
                </motion.div>
            </motion.div>
        </AnimatePresence>
    );
};

const Footer = () => {
    const [activePopup, setActivePopup] = useState(null);

    return (
        <>
            <motion.footer
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                className="relative py-4 mt-12 text-center"
            >
               
                <div className="absolute inset-0 bg-black opacity-50" />
                <div className="relative z-10">
                    <p className="text-white text-sm">
                        © 2025 JOOD. All rights reserved.
                    </p>
                    <div className="mt-8 space-x-6">
                        <button
                            onClick={() => setActivePopup("privacyPolicy")}
                            className="text-white text-sm hover:bg-green-500/20 hover:text-green-500 rounded-full px-3 py-1 transition-all duration-300"
                        >
                            Privacy Policy
                        </button>
                        <button
                            onClick={() => setActivePopup("termsOfService")}
                            className="text-white text-sm hover:bg-green-500/20 hover:text-green-500 rounded-full px-3 py-1 transition-all duration-300"
                        >
                            Terms of Service
                        </button>
                        <a
                            href="/ContactPage"
                            className="text-white text-sm hover:bg-green-500/20 hover:text-green-500 rounded-full px-3 py-1 transition-all duration-300"
                        >
                            Contact
                        </a>
                        <a
                            href="/about-us"
                            className="text-white text-sm hover:bg-green-500/20 hover:text-green-500 rounded-full px-3 py-1 transition-all duration-300"
                        >
                            About Us
                        </a>
                    </div>
                </div>
            </motion.footer>

            {activePopup && (
                <LegalPopup
                    type={activePopup}
                    onClose={() => setActivePopup(null)}
                />
            )}
        </>
    );
};

export default Footer;
